on:
  schedule:
    - cron: '*/5 * * * *'  # Every 5 minutes
  workflow_dispatch:       # Optional: allows manual trigger

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Random chance to ping
        id: choice
        run: |
          CHANCE=$((RANDOM % 5))
          echo "chance=$CHANCE" >> $GITHUB_OUTPUT

      - name: Ping endpoint
        if: steps.choice.outputs.chance == '0'
        run: |
          curl -sf https://my-dragonnews-server.onrender.com/ping && echo "✅ pong"
       
